export function Spinner({size='md',className=''}){const s={sm:'w-5 h-5 border-2',md:'w-8 h-8 border-[3px]',lg:'w-12 h-12 border-4'};return<div className={`spinner ${s[size]} ${className}`}/>;}
export function FullPageSpinner(){return<div className="min-h-[60vh] flex flex-col items-center justify-center gap-4"><div className="w-10 h-10 spinner"/><span className="text-sm text-[#5a6e63]">Loading…</span></div>;}
export function EmptyState({icon='📭',title,message,action}){return<div className="flex flex-col items-center justify-center py-16 px-4 text-center"><div className="text-5xl mb-4">{icon}</div><h3 className="text-lg font-bold text-[#1a2e23] mb-2">{title}</h3>{message&&<p className="text-sm text-[#5a6e63] max-w-xs mb-6">{message}</p>}{action}</div>;}
const SM={active:'bg-green-50 text-green-700',pending:'bg-yellow-50 text-yellow-700',expired:'bg-red-50 text-red-600',confirmed:'bg-blue-50 text-blue-700',cancelled:'bg-gray-100 text-gray-500',completed:'bg-purple-50 text-purple-700',rented:'bg-teal-50 text-teal-700',suspended:'bg-red-100 text-red-700',no_show:'bg-orange-50 text-orange-600',failed:'bg-red-50 text-red-600',timeout:'bg-gray-100 text-gray-500'};
export function StatusBadge({status,className=''}){return<span className={`badge ${SM[status]||'bg-gray-100 text-gray-600'} capitalize ${className}`}>{status?.replace(/_/g,' ')}</span>;}
export function SectionHeader({title,highlight,subtitle,action}){return<div className="flex items-end justify-between mb-8 gap-4 flex-wrap"><div><h2 className="section-title text-[#1a2e23]">{title} {highlight&&<span className="text-green-600">{highlight}</span>}</h2>{subtitle&&<p className="section-sub mt-1">{subtitle}</p>}</div>{action}</div>;}
export function SkeletonCard(){return<div className="card overflow-hidden"><div className="skeleton h-48 w-full"/><div className="p-4 space-y-3"><div className="skeleton h-3 w-1/3 rounded-full"/><div className="skeleton h-5 w-3/4 rounded-full"/><div className="skeleton h-3 w-1/2 rounded-full"/><div className="skeleton h-6 w-1/3 rounded-full mt-2"/></div></div>;}
export function Countdown({expiresAt}){const diff=new Date(expiresAt)-new Date();if(diff<=0)return<span className="text-xs text-red-500 font-semibold">Expired</span>;const days=Math.floor(diff/86400000),hours=Math.floor((diff%86400000)/3600000);return<span className={`text-xs font-semibold ${days<1?'text-red-500':days<2?'text-yellow-600':'text-green-600'}`}>⏰ {days>0?`${days}d ${hours}h left`:`${hours}h left`}</span>;}
export function AmenityTag({label}){return<span className="amenity-tag">{label}</span>;}
const RL={single_room:'Single Room',bedsitter:'Bedsitter',one_bedroom:'1 Bedroom',two_bedroom:'2 Bedrooms',three_bedroom:'3 Bedrooms',four_bedroom_plus:'4+ Bedrooms',studio:'Studio'};
export function roomLabel(t){return RL[t]||t;}
export function Ksh({amount}){return<span>KSh {Number(amount).toLocaleString()}</span>;}
