const router=require('express').Router(),{authenticate,authorize}=require('../middleware/auth.middleware'),{query}=require('../config/database');
router.use(authenticate,authorize('admin'));
router.get('/stats',async(req,res,next)=>{try{const[u,l,b,p,pend]=await Promise.all([query("SELECT COUNT(*) FROM users"),query("SELECT COUNT(*) FROM listings WHERE status='active'"),query("SELECT COUNT(*) FROM bookings"),query("SELECT COALESCE(SUM(amount),0) as total FROM payments WHERE status='completed'"),query("SELECT COUNT(*) FROM listings WHERE status='pending'")]);res.json({users:parseInt(u.rows[0].count),activeListings:parseInt(l.rows[0].count),bookings:parseInt(b.rows[0].count),revenue:parseInt(p.rows[0].total),pendingListings:parseInt(pend.rows[0].count)});}catch(err){next(err);}});
router.get('/listings',async(req,res,next)=>{try{const{status='pending',page=1,limit=20}=req.query;const{rows}=await query(`SELECT l.*,u.first_name,u.last_name,u.email,u.phone FROM listings l JOIN users u ON u.id=l.landlord_id WHERE l.status=$1 ORDER BY l.created_at DESC LIMIT $2 OFFSET $3`,[status,limit,(page-1)*limit]);res.json({listings:rows});}catch(err){next(err);}});
router.patch('/listings/:id/approve',async(req,res,next)=>{try{await query("UPDATE listings SET status='active',published_at=NOW() WHERE id=$1",[req.params.id]);res.json({message:'Approved'});}catch(err){next(err);}});
router.patch('/listings/:id/suspend',async(req,res,next)=>{try{await query("UPDATE listings SET status='suspended' WHERE id=$1",[req.params.id]);res.json({message:'Suspended'});}catch(err){next(err);}});
router.get('/users',async(req,res,next)=>{try{const{rows}=await query("SELECT id,first_name,last_name,email,phone,role,is_verified,is_active,created_at FROM users ORDER BY created_at DESC LIMIT 100");res.json({users:rows});}catch(err){next(err);}});
router.patch('/users/:id/toggle',async(req,res,next)=>{try{const{rows}=await query("UPDATE users SET is_active=NOT is_active WHERE id=$1 RETURNING id,is_active",[req.params.id]);res.json({user:rows[0]});}catch(err){next(err);}});
module.exports=router;
